name: kamao
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  otp_text_field: ^1.1.3
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  get: ^4.6.5
  dash: ^1.0.5
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.0.20
  another_flushbar: ^1.12.29
  flutter_svg: ^2.0.4
  timeago:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.6.0
  dio: ^5.1.0
  logger: ^1.3.0
  webview_flutter: ^4.0.7
  uni_links: ^0.5.1
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  package_info_plus: ^3.0.3
  share_plus: ^6.3.1

  responsive_sizer:
  carousel_slider: ^4.2.1
  flutter_dash:
  syncfusion_flutter_sliders: ^20.4.48
  badges:
  percent_indicator: ^4.2.2
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  fluttertoast: ^8.1.2
  sms_otp_auto_verify: ^2.1.0
  get_storage: ^2.0.3
  camera: ^0.9.7+1
  dropdown_formfield: ^0.1.4
  intl:
  image_picker: ^0.8.3+1
  dotted_border: ^2.0.0+3
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/png/icons/
    - assets/fonts/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
        - asset: assets/fonts/DMSans-Regular.ttf

  uses-material-design: true
